In [1]:
import os
#print(os.getcwd())
os.chdir("../")
#print(os.getcwd())

In [3]:
import pandas as pd

csv_name_r = "random_4090.csv"
csv_name_ig = "integratedgradients_4090.csv"
csv_name_l = "lime_4090.csv"
csv_name_sg = "smoothgrad_4090.csv"

df_r = pd.read_csv(os.path.join("csv_results", csv_name_r))
df_ig = pd.read_csv(os.path.join("csv_results", csv_name_ig))
df_lime = pd.read_csv(os.path.join("csv_results", csv_name_l))
df_sg = pd.read_csv(os.path.join("csv_results", csv_name_sg))

In [4]:
df_r

,id,generation,elapsed,misbehaviour,expected_label,predicted_label,text,gpt,validity,gpt2,validity_gpt2,gpt3,validity_gpt3,gpt4,validity_gpt4,gpt5,validity_gpt5
0,1,29,7.839830,True,0,1,<start> i have to say is the only reason i eve...,negative,0,negative,0,negative,0,negative,0,negative,0
1,4,39,10.020275,True,0,1,<start> the movie had an interesting and inter...,negative,0,negative,0,negative,0,negative,0,negative,0
2,8,51,12.382502,True,0,1,<start> like many people in my general and uni...,negative,0,negative,0,negative,0,negative,0,negative,0
3,13,33,8.666420,True,0,1,<start> r i and ace c c o is the stupidest and...,negative,0,negative,0,negative,0,negative,0,negative,0
4,14,26,7.208628,True,0,1,<start> one of the worst films of it's genre a...,negative,0,negative,0,negative,0,invalid,-1,negative,0
5,15,50,12.189461,True,0,1,<start> ludicrously and laughably terribly and...,negative,0,negative,0,negative,0,negative,0,negative,0
6,21,12,4.135082,True,0,1,<start> it's unlikely that anyone except those...,negative,0,negative,0,negative,0,negative,0,negative,0
7,25,2,1.736742,True,1,0,<start> such a shame that this wonderful brigh...,negative,0,negative,0,positive,1,negative,0,negative,0
8,26,61,14.238987,True,0,1,<start> miserable and execrable film non and n...,negative,0,negative,0,negative,0,negative,0,negative,0
9,30,3,1.990316,True,1,0,<start> i <unk> to the library to check out th...,negative,0,negative,0,negative,0,negative,0,negative,0
10,31,38,9.688026,True,0,1,<start> we chose to see this motion picture as...,negative,0,negative,0,negative,0,negative,0,negative,0
11,32,62,14.429301,True,0,1,<start> unreal and contrived melodrama with a ...,negative,0,negative,0,negative,0,negative,0,negative,0
12,33,12,4.130538,True,0,1,<start> though it's better and respectable tha...,negative,0,negative,0,negative,0,negative,0,negative,0
13,37,78,17.331033,True,0,1,<start> this extremely low and humble budget m...,negative,0,negative,0,negative,0,negative,0,negative,0
14,42,3,1.985687,True,1,0,<start> i'm torn about this show while most pa...,positive,1,positive,1,positive,1,positive,1,positive,1
15,44,64,14.788859,True,0,1,<start> predict this a sunday school movie pow...,negative,0,negative,0,negative,0,negative,0,negative,0
16,52,6,2.725944,True,0,1,<start> br br as a fan of bad and spoilt movie...,negative,0,negative,0,negative,0,negative,0,negative,0
17,59,16,5.017662,True,0,1,<start> if you watched the series and love the...,negative,0,negative,0,negative,0,negative,0,negative,0
18,62,73,16.451776,True,0,1,<start> what was he thinking how drab an worke...,negative,0,negative,0,negative,0,negative,0,negative,0
19,66,5,2.474275,True,1,0,<start> a town in japan is being taken over by...,positive,1,positive,1,positive,1,positive,1,positive,1
20,70,27,7.398936,True,0,1,<start> i thought this serial was going to be ...,negative,0,negative,0,negative,0,negative,0,negative,0
21,71,37,9.467207,True,0,1,<start> i hated the book a guy and make fun me...,negative,0,negative,0,negative,0,negative,0,negative,0
22,84,64,14.773161,True,0,1,<start> well this picture suggest wasn't as ho...,negative,0,negative,0,negative,0,negative,0,negative,0
23,86,85,18.510898,True,1,0,<start> personally and in person one and one d...,negative,0,negative,0,positive,1,positive,1,positive,1
24,87,19,5.671460,True,0,1,<start> i hold to watch this one for my canadi...,negative,0,negative,0,negative,0,negative,0,negative,0
25,89,26,7.179004,True,0,1,<start> this pathetic and wretched pardon and ...,negative,0,negative,0,negative,0,negative,0,negative,0
26,91,65,15.042025,True,1,0,<start> well and comfortably i tend to watch a...,negative,0,negative,0,negative,0,invalid,-1,invalid,-1
27,94,84,18.335519,True,1,0,<start> this has got to be ace and ace of the ...,positive,1,positive,1,positive,1,positive,1,positive,1
28,98,85,18.506361,True,0,1,<start> how any of you gave this to a greater ...,negative,0,negative,0,negative,0,negative,0,negative,0
29,100,80,17.651482,True,0,1,<start> there and at that place are many myste...,negative,0,negative,0,negative,0,negative,0,negative,0
30,102,20,5.883490,True,0,1,<start> this is an example of a movie that can...,negative,0,negative,0,negative,0,negative,0,negative,0
31,103,43,10.782036,True,0,1,<start> after a string of successful 'a adult ...,invalid,-1,invalid,-1,invalid,-1,invalid,-1,invalid,-1
32,107,20,5.881606,True,0,1,<start> i came across this film by accident an...,negative,0,negative,0,negative,0,negative,0,negative,0
33,113,73,16.431716,True,1,0,<start> if you can look on a amaze and amaze t...,invalid,-1,invalid,-1,invalid,-1,invalid,-1,invalid,-1
34,115,27,7.381244,True,0,1,<start> this movie started out as a quite and ...,negative,0,negative,0,negative,0,negative,0,negative,0
35,117,20,5.877729,True,0,1,<start> endless and eternal repetition most th...,negative,0,negative,0,negative,0,negative,0,negative,0
36,118,93,19.862448,True,0,1,<start> the best and ripe fix forth in this pi...,negative,0,negative,0,negative,0,negative,0,negative,0
37,120,3,1.954884,True,0,1,sweet <unk> into each other's ears almost to t...,negative,0,negative,0,negative,0,negative,0,negative,0
38,121,2,1.698853,True,0,1,<start> mr wonders if this movie was produced ...,negative,0,negative,0,negative,0,negative,0,negative,0
39,124,45,11.172300,True,0,1,<start> love the but this was a lame episode d...,negative,0,negative,0,negative,0,negative,0,negative,0
40,125,16,4.991651,True,1,0,<start> i first and offset saw this short when...,positive,1,positive,1,positive,1,positive,1,positive,1
41,127,36,9.240915,True,0,1,<start> the few scenes that actually attempt a...,negative,0,negative,0,negative,0,negative,0,negative,0
42,132,6,2.694379,True,0,1,<start> wow even american idol and so you thin...,negative,0,negative,0,negative,0,negative,0,negative,0
43,135,11,3.855614,True,0,1,<start> a stock fish and angle out of water st...,negative,0,negative,0,negative,0,negative,0,negative,0
44,140,56,13.274232,True,0,1,<start> why are there no good and upright revi...,negative,0,negative,0,negative,0,negative,0,negative,0
45,147,57,13.455973,True,1,0,<start> this movie is a must determine and see...,invalid,-1,invalid,-1,invalid,-1,invalid,-1,invalid,-1
46,149,2,1.687998,True,0,1,<start> my friends and i rented this movie <un...,positive,1,positive,1,positive,1,negative,0,negative,0
47,152,47,11.549741,True,0,1,<start> i and 1 cause never always and invaria...,negative,0,negative,0,negative,0,negative,0,negative,0
48,155,5,2.439354,True,0,1,<start> this movie is ace of the poorest and p...,negative,0,negative,0,negative,0,negative,0,negative,0
49,156,6,2.685208,True,0,1,<start> i expected this movie to be absolutely...,negative,0,negative,0,negative,0,negative,0,negative,0
50,158,6,2.684458,True,0,1,<start> if i had to pick the most depressing m...,negative,0,negative,0,negative,0,negative,0,negative,0
51,160,95,20.180052,True,1,0,<start> train and discipline someone you love ...,invalid,-1,invalid,-1,invalid,-1,invalid,-1,invalid,-1
52,163,30,7.985070,True,1,0,<start> this make up and improving a good enou...,negative,0,negative,0,negative,0,negative,0,negative,0
53,168,56,13.263316,True,0,1,br people don't go on trips like this for coll...,negative,0,negative,0,negative,0,negative,0,negative,0
54,169,54,12.885260,True,0,1,<start> this is by former armed forces and old...,negative,0,negative,0,negative,0,negative,0,negative,0
55,170,47,11.542686,True,0,1,<start> first and number 1 off let me say 1 se...,negative,0,negative,0,negative,0,negative,0,negative,0

In [5]:
NGEN = 100
import numpy as np

def cumulative_csv(df):
    col_names = ['generation', 'num', 'validity', 'preservation']

    df_cum = pd.DataFrame(columns= col_names)
    df_cum.generation = np.linspace(1,NGEN,NGEN)
    # df['generation'].cumsum()

    for i in range(len(df_cum)):
        df_cum.at[i, "num"] = (df['generation'] == i).sum()
        df_cum.at[i, "validity"] = ((df['generation'] == i) & (df['validity']>=0)).sum()
        df_cum.at[i, "preservation"] = ((df['generation'] == i) & (df['validity'] == df['expected_label'].astype('int'))).sum()

    df_cum['cum_num']  = df_cum['num'].cumsum()
    df_cum['cum_validity']  = df_cum['validity'].cumsum()
    df_cum['cum_preservation']  = df_cum['preservation'].cumsum()
    df_cum['auc_cum_num'] = df_cum['cum_num'].cumsum()
    return df_cum

In [6]:
df_cum_random = cumulative_csv(df_r)
df_cum_sg = cumulative_csv(df_sg)
df_cum_ig = cumulative_csv(df_ig)
df_cum_lime = cumulative_csv(df_lime)

In [7]:
df_cum_random

,generation,num,validity,preservation,cum_num,cum_validity,cum_preservation,auc_cum_num
0,1.0,0,0,0,0,0,0,0
1,2.0,0,0,0,0,0,0,0
2,3.0,3,3,1,3,3,1,3
3,4.0,3,3,2,6,6,3,9
4,5.0,0,0,0,6,6,3,15
...,...,...,...,...,...,...,...,...
95,96.0,1,0,0,56,52,46,3265
96,97.0,0,0,0,56,52,46,3321
97,98.0,0,0,0,56,52,46,3377
98,99.0,0,0,0,56,52,46,3433
99,100.0,0,0,0,56,52,46,3489

In [8]:
df_cum_sg

,generation,num,validity,preservation,cum_num,cum_validity,cum_preservation,auc_cum_num
0,1.0,0,0,0,0,0,0,0
1,2.0,0,0,0,0,0,0,0
2,3.0,6,6,5,6,6,5,6
3,4.0,5,5,5,11,11,10,17
4,5.0,2,2,2,13,13,12,30
...,...,...,...,...,...,...,...,...
95,96.0,0,0,0,95,85,69,6224
96,97.0,0,0,0,95,85,69,6319
97,98.0,0,0,0,95,85,69,6414
98,99.0,0,0,0,95,85,69,6509
99,100.0,0,0,0,95,85,69,6604

In [11]:
from data_analysis.stat_tests import *


pds = [df_cum_sg, df_cum_lime, df_cum_ig]
test_name = ['smoothgrad', 'lime', 'ig']

for df, name in zip(pds, test_name):
    pvalue, cohensd = run_wilcoxon_and_cohend(df["cum_num"], df_cum_random["cum_num"])
    print("------------------------------------------------------",name, "{:.2E}".format(pvalue), cohensd[0])

statistic is: 0.0 P-Value is: 6.929188414583868e-18
Cohen's D is: ('large', 1.4552099307545343)
------------------------------------------------------ smoothgrad 6.93E-18 large
statistic is: 0.0 P-Value is: 1.1739051598915815e-17
Cohen's D is: ('large', 1.933036633920566)
------------------------------------------------------ lime 1.17E-17 large
statistic is: 0.0 P-Value is: 7.896658460485097e-18
Cohen's D is: ('large', 2.0810668784683974)
------------------------------------------------------ ig 7.90E-18 large

In [12]:
methods = ["smoothgrad", "integratedgradients", "lime", "random"]
df_summary = pd.DataFrame(columns=["generation"] + methods)
df_summary['generation'] = np.linspace(9,99,10)
method_dfs =  {"smoothgrad":df_cum_sg, "integratedgradients":df_cum_ig, "lime":df_cum_lime, "random":df_cum_random}

In [8]:
np.linspace(9,99,10)

array([ 9., 19., 29., 39., 49., 59., 69., 79., 89., 99.])

In [9]:
df_tmp_random = pd.merge(df_cum_random[['generation', 'cum_num', 'auc_cum_num']],
                          df_summary['generation'], on='generation', how='right')

In [10]:
for met in methods:
    df_tmp = pd.merge(method_dfs[met][['generation', 'cum_num', 'auc_cum_num']], 
                      df_summary['generation'], on='generation', how='right')
    for i in range(len(df_summary)):
        df_summary.at[i, met] = ("& " +"{:.2f}".format(df_tmp.at[i, 'cum_num']/174*100) +'/' + 
        "{:.2f}".format(df_tmp.at[i, 'auc_cum_num']/df_tmp_random.at[i, 'auc_cum_num']) )

In [11]:
(df_tmp_random['cum_num']/174*100)

0     6.896552
1     9.770115
2    14.367816
3    17.816092
4    20.689655
5    24.137931
6    27.011494
7    28.735632
8    31.034483
9    32.183908
Name: cum_num, dtype: object

In [12]:
print("{:.2f}".format(df_tmp.at[i, 'cum_num']/174*100))
print("{:.2f}".format(df_tmp.at[i, 'auc_cum_num']/df_tmp_random.at[i, 'auc_cum_num']*100))

32.18
100.00

In [13]:
"{:.2f}".format(df_tmp_random.at[7, 'cum_num']/174*100)

'28.74'

In [14]:
df_summary

   generation    smoothgrad integratedgradients          lime        random
0         9.0  & 13.79/1.93        & 16.09/2.05  & 10.92/1.44   & 6.90/1.00
1        19.0  & 21.84/2.08        & 31.03/2.71  & 32.18/2.31   & 9.77/1.00
2        29.0  & 30.46/2.08        & 45.98/2.92  & 42.53/2.74  & 14.37/1.00
3        39.0  & 39.08/2.12        & 56.90/3.05  & 50.57/2.82  & 17.82/1.00
4        49.0  & 41.38/2.12        & 63.79/3.09  & 59.77/2.86  & 20.69/1.00
5        59.0  & 46.55/2.08        & 66.67/3.04  & 62.64/2.83  & 24.14/1.00
6        69.0  & 48.85/2.03        & 69.54/2.94  & 65.52/2.75  & 27.01/1.00
7        79.0  & 50.57/1.98        & 73.56/2.87  & 69.54/2.69  & 28.74/1.00
8        89.0  & 52.87/1.93        & 75.86/2.80  & 72.41/2.64  & 31.03/1.00
9        99.0  & 54.60/1.90        & 76.44/2.74  & 75.86/2.59  & 32.18/1.00